name: conjur-action Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  authn-jwt:
    runs-on: self-hosted
    
    permissions:
      id-token: 'write'
      contents: 'read'

    steps:
      - uses: actions/checkout@v1
      - name: Use CyberArk Conjur Secret Fetcher w/ GitHub JWT
        uses: ./
        with:
          url: ${{ secrets.CONJUR_URL }}
          account: cyberarkdemo
          authn_id: ${{ secrets.AUTHN_ID }}
          secrets: data/vault/D_ZH_PAM_akv-cyberark-secmgr/SM-POC-Secret1/username|sql_username
      - name: Check SQL_USERNAME Outside Docker Container for Secret Masking
        run: printenv SQL_USERNAME | sed 's/./& /g
