
# This is a basic workflow to help you get started with Actions
name: CI
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  authn-jwt:
    # The type of runner that the job will run on
    runs-on: self-hosted
    
    permissions:
      id-token: 'write'
      contents: 'read'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 
      - name: Use My Custom Action
        run: |
          conjur login -u sh917si -p 'mZs?9txXN(GU:~gY:b)HN'
      - name: Verify Conjur Login
        run: |
            conjur whoami   
      #   with: # Repository name with owner. actions/checkout 
      #     Default: ${{ github.repository }}
      #     url: https://ab.id.cyberark.cloud
      #     account: conjur
      #     authn_id: authn-jwt/dev
      #     secrets: data/vault/D_ZH_PAM_akv-cyberark-secmgr/SM-POC-Secret1/username|sql_username;data/vault/D_ZH_PAM_akv-cyberark-secmgr/SM-POC-Secret1/password|sql_password
      # - name: Check SQL_USERNAME Outside Docker Container for Secret Masking
      #   run: printenv SQL_USERNAME | sed 's/./& /g'
      # - name: Check SQL_PASSWORD Outside Docker Container for Secret Masking
      #   run: printenv SQL_PASSWORD | sed 's/./& /g'
